export type CategoryLawyer = {
  id: string;
  name: string;
  city: string;
  court: string;
  specialization: string;
  expertise: string[];
  rating: number;
  price: number;
  responseTime: string;
  isOnline: boolean;
  category: string;
};

export const LAWYERS: CategoryLawyer[] = [
  // Family Law
  {
    id: 'FL1',
    name: 'Adv. Priya Sharma',
    city: 'Delhi',
    court: 'High Court',
    specialization: 'Family Law',
    expertise: ['Divorce', 'Custody', '498A'],
    rating: 4.9,
    price: 25,
    responseTime: '1 min',
    isOnline: true,
    category: 'Family Law',
  },
  {
    id: 'FL2',
    name: 'Adv. Karan Malhotra',
    city: 'Mumbai',
    court: 'Family Court',
    specialization: 'Family Law',
    expertise: ['Maintenance', 'Domestic Violence'],
    rating: 4.7,
    price: 20,
    responseTime: '3 mins',
    isOnline: true,
    category: 'Family Law',
  },
  {
    id: 'FL3',
    name: 'Adv. Isha Verma',
    city: 'Chandigarh',
    court: 'District Court',
    specialization: 'Family Law',
    expertise: ['Mutual Divorce', 'Alimony'],
    rating: 4.6,
    price: 18,
    responseTime: '4 mins',
    isOnline: false,
    category: 'Family Law',
  },

  // Criminal Law
  {
    id: 'CL1',
    name: 'Adv. Rahul Mehta',
    city: 'Delhi',
    court: 'Sessions Court',
    specialization: 'Criminal Law',
    expertise: ['FIR', 'Bail', 'Defense'],
    rating: 4.8,
    price: 30,
    responseTime: '2 mins',
    isOnline: true,
    category: 'Criminal Law',
  },
  {
    id: 'CL2',
    name: 'Adv. Sneha Reddy',
    city: 'Hyderabad',
    court: 'High Court',
    specialization: 'Criminal Law',
    expertise: ['Cyber Crime', 'Fraud'],
    rating: 4.6,
    price: 22,
    responseTime: '4 mins',
    isOnline: false,
    category: 'Criminal Law',
  },
  {
    id: 'CL3',
    name: 'Adv. Manoj Arora',
    city: 'Pune',
    court: 'Sessions Court',
    specialization: 'Criminal Law',
    expertise: ['Anticipatory Bail', 'Trial'],
    rating: 4.7,
    price: 24,
    responseTime: '3 mins',
    isOnline: true,
    category: 'Criminal Law',
  },

  // Property & Real Estate
  {
    id: 'PL1',
    name: 'Adv. Anjali Kapoor',
    city: 'Bangalore',
    court: 'High Court',
    specialization: 'Property Law',
    expertise: ['RERA', 'Land Disputes'],
    rating: 4.9,
    price: 25,
    responseTime: '2 mins',
    isOnline: true,
    category: 'Property & Real Estate',
  },
  {
    id: 'PL2',
    name: 'Adv. Amit Singh',
    city: 'Lucknow',
    court: 'District Court',
    specialization: 'Property Law',
    expertise: ['Registry', 'Title Issues'],
    rating: 4.5,
    price: 18,
    responseTime: '5 mins',
    isOnline: true,
    category: 'Property & Real Estate',
  },
  {
    id: 'PL3',
    name: 'Adv. Kavya Bhat',
    city: 'Pune',
    court: 'Civil Court',
    specialization: 'Property Law',
    expertise: ['Tenant Disputes', 'Eviction'],
    rating: 4.6,
    price: 19,
    responseTime: '4 mins',
    isOnline: false,
    category: 'Property & Real Estate',
  },

  // Employment & Labour
  {
    id: 'EL1',
    name: 'Adv. Neha Iyer',
    city: 'Chennai',
    court: 'Labour Court',
    specialization: 'Employment Law',
    expertise: ['Salary', 'Termination'],
    rating: 4.7,
    price: 20,
    responseTime: '2 mins',
    isOnline: true,
    category: 'Employment & Labour',
  },
  {
    id: 'EL2',
    name: 'Adv. Ritesh Saha',
    city: 'Bangalore',
    court: 'Labour Court',
    specialization: 'Employment Law',
    expertise: ['POSH', 'PF/ESI'],
    rating: 4.8,
    price: 23,
    responseTime: '3 mins',
    isOnline: true,
    category: 'Employment & Labour',
  },

  // Banking & Finance
  {
    id: 'BF1',
    name: 'Adv. Saurabh Jain',
    city: 'Mumbai',
    court: 'DRT',
    specialization: 'Banking Law',
    expertise: ['SARFAESI', 'Loan Disputes'],
    rating: 4.7,
    price: 26,
    responseTime: '2 mins',
    isOnline: true,
    category: 'Banking & Finance',
  },
  {
    id: 'BF2',
    name: 'Adv. Meenal Rao',
    city: 'Delhi',
    court: 'High Court',
    specialization: 'Finance Law',
    expertise: ['Cheque Bounce', 'Recovery'],
    rating: 4.6,
    price: 22,
    responseTime: '4 mins',
    isOnline: false,
    category: 'Banking & Finance',
  },

  // Consumer Protection
  {
    id: 'CP1',
    name: 'Adv. Arjun Bedi',
    city: 'Chandigarh',
    court: 'Consumer Court',
    specialization: 'Consumer Law',
    expertise: ['Defective Products', 'Refund Claims'],
    rating: 4.8,
    price: 21,
    responseTime: '2 mins',
    isOnline: true,
    category: 'Consumer Protection',
  },
  {
    id: 'CP2',
    name: 'Adv. Sana Khan',
    city: 'Hyderabad',
    court: 'Consumer Commission',
    specialization: 'Consumer Law',
    expertise: ['E-commerce', 'Service Deficiency'],
    rating: 4.6,
    price: 19,
    responseTime: '5 mins',
    isOnline: true,
    category: 'Consumer Protection',
  },

  // Cyber Law
  {
    id: 'CY1',
    name: 'Adv. Rohan Deshmukh',
    city: 'Pune',
    court: 'Cyber Cell',
    specialization: 'Cyber Law',
    expertise: ['UPI Fraud', 'Data Theft'],
    rating: 4.8,
    price: 24,
    responseTime: '2 mins',
    isOnline: true,
    category: 'Cyber Law',
  },
  {
    id: 'CY2',
    name: 'Adv. Nisha Gupta',
    city: 'Delhi',
    court: 'High Court',
    specialization: 'Cyber Law',
    expertise: ['Defamation', 'Cyber Harassment'],
    rating: 4.7,
    price: 23,
    responseTime: '3 mins',
    isOnline: false,
    category: 'Cyber Law',
  },

  // Corporate & Business
  {
    id: 'CB1',
    name: 'Adv. Varun Sethi',
    city: 'Mumbai',
    court: 'NCLT',
    specialization: 'Corporate Law',
    expertise: ['Contracts', 'Startup Compliance'],
    rating: 4.9,
    price: 28,
    responseTime: '2 mins',
    isOnline: true,
    category: 'Corporate & Business',
  },
  {
    id: 'CB2',
    name: 'Adv. Aditi Menon',
    city: 'Bangalore',
    court: 'High Court',
    specialization: 'Corporate Law',
    expertise: ['IP', 'Founders Agreement'],
    rating: 4.7,
    price: 26,
    responseTime: '3 mins',
    isOnline: true,
    category: 'Corporate & Business',
  },

  // Documentation & Civil
  {
    id: 'DC1',
    name: 'Adv. Hemant Tiwari',
    city: 'Lucknow',
    court: 'Civil Court',
    specialization: 'Civil Law',
    expertise: ['Legal Notice', 'Affidavits'],
    rating: 4.5,
    price: 17,
    responseTime: '5 mins',
    isOnline: true,
    category: 'Documentation & Civil',
  },
  {
    id: 'DC2',
    name: 'Adv. Pooja Nair',
    city: 'Chennai',
    court: 'Civil Court',
    specialization: 'Civil Law',
    expertise: ['Will Drafting', 'Civil Suits'],
    rating: 4.6,
    price: 18,
    responseTime: '4 mins',
    isOnline: false,
    category: 'Documentation & Civil',
  },

  // Litigation Support
  {
    id: 'LS1',
    name: 'Adv. Deepak Kulkarni',
    city: 'Delhi',
    court: 'Supreme Court',
    specialization: 'Litigation',
    expertise: ['Appeals', 'Stay Orders'],
    rating: 4.8,
    price: 29,
    responseTime: '2 mins',
    isOnline: true,
    category: 'Litigation Support',
  },
  {
    id: 'LS2',
    name: 'Adv. Reema Chawla',
    city: 'Mumbai',
    court: 'High Court',
    specialization: 'Litigation',
    expertise: ['Execution', 'Writs'],
    rating: 4.7,
    price: 27,
    responseTime: '3 mins',
    isOnline: true,
    category: 'Litigation Support',
  },
];

export const getLawyersByCategory = (category: string): CategoryLawyer[] =>
  LAWYERS
    .filter((l) => l.category === category)
    .sort((a, b) => Number(b.isOnline) - Number(a.isOnline) || b.rating - a.rating)
    .slice(0, 3);

